# Site Settings
title: Kai Wang
url: 'https://wangjinjie722.github.io'
baseurl: ''
description: "Kai Wang - Senior ML Engineer | RecSys Researcher | Game AI Enthusiast"

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
encoding: "utf-8"

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Google Analytics
google_analytics: G-PT9LJDYPGD
